### ISSUE TITLE
stscharts not launching

### ISSUE THREAD

**Issue by jokey2k** [topological-state/stskit#106]
When running from commit [8104f5d](https://github.com/topological-state/stskit/commit/8104f5d0f600411092cad0e9aaba4dcd3a98fa2e)

python 3.11.1 x64 on windows

---

C:\Users\jokey\Downloads\stskit-master>\Users\jokey\AppData\Local\Programs\Python\Python311\python.exe stscharts.py
Traceback (most recent call last):
  File "C:\Users\mail\Downloads\stskit-master\stscharts.py", line 4, in <module>
    main()
  File "C:\Users\mail\Downloads\stskit-master\stskit\__main__.py", line 324, in main
    qtrio.run(main_window)
  File "C:\Users\jokey\AppData\Local\Programs\Python\Python311\Lib\site-packages\qtrio\_core.py", line 513, in run
    return runner.outcomes.unwrap()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jokey\AppData\Local\Programs\Python\Python311\Lib\site-packages\qtrio\_core.py", line 472, in unwrap
    result = self.trio.unwrap()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jokey\AppData\Local\Programs\Python\Python311\Lib\site-packages\outcome\_impl.py", line 138, in unwrap
    raise captured_error
  File "C:\Users\jokey\AppData\Local\Programs\Python\Python311\Lib\site-packages\qtrio\_core.py", line 720, in trio_main    result = await async_fn(*args)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mail\Downloads\stskit-master\stskit\__main__.py", line 306, in main_window
    async with trio.open_nursery() as nursery:
  File "C:\Users\jokey\AppData\Local\Programs\Python\Python311\Lib\site-packages\trio\_core\_run.py", line 850, in __aexit__
    raise combined_error_from_nursery
  File "C:\Users\mail\Downloads\stskit-master\stskit\__main__.py", line 253, in update_loop
    await self.zentrale.update()
  File "C:\Users\mail\Downloads\stskit-master\stskit\zentrale.py", line 117, in update
    self.planung.verspaetungen_korrigieren()
  File "C:\Users\mail\Downloads\stskit-master\stskit\planung.py", line 1484, in verspaetungen_korrigieren
    ziel.auto_korrektur.ankunft_berechnen(self.zielgraph, node, data)
  File "C:\Users\mail\Downloads\stskit-master\stskit\planung.py", line 196, in ankunft_berechnen
    ankunft = max(ankunft or 0, pred_p_ab + pred_v_ab)
                                ~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by jokey2k** [comment]
Used with Hamburg-Harburg in online session

**Comment by topological-state** [comment]
thanks for the message. does this happen in a sandbox session as well?

**Comment by topological-state** [comment]
can't reproduce at hamburg-harburg online and sandbox (python 3.10 on linux). a workaround for the type error has been proposed.
