### ISSUE TITLE
Fehler seit neustem Update

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#107]
>   File "\stskit-master\stskit\fahrplan.py", line 300, in data
    return str(zeile.auto_korrektur)
  File "\stskit-master\stskit\planung.py", line 569, in __str__
    return f"{self.display_name} → {self.folge_name}"
  File "\stskit-master\stskit\planung.py", line 412, in folge_name
    return self._folge.zid
AttributeError: 'KupplungUrsprung' object has no attribute '_folge'
Traceback (most recent call last):
  File "\stskit-master\stskit\planung.py", line 410, in folge_name
    return self._planung.zielgraph.nodes[self._folge]['obj'].zug.name
AttributeError: 'KupplungUrsprung' object has no attribute '_folge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\stskit-master\stskit\fahrplan.py", line 300, in data
    return str(zeile.auto_korrektur)
  File "\stskit-master\stskit\planung.py", line 569, in __str__
    return f"{self.display_name} → {self.folge_name}"
  File "\stskit-master\stskit\planung.py", line 412, in folge_name
    return self._folge.zid
AttributeError: 'KupplungUrsprung' object has no attribute '_folge'

**Comment by topological-state** [comment]
Sorry!
