### ISSUE TITLE
SAXParseException: unclosed token

### ISSUE THREAD

**Issue by topological-state** [topological-state/stskit#129]
nach drei stunden spielzeit in basel rb crasht das programm mit einer SAXParseException:

```
Traceback (most recent call last):
  File "miniconda3/envs/sts/lib/python3.9/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: unclosed token: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stskit/stskit/stsdispo.py", line 4, in <module>
    main()
  File "stskit/stskit/__main__.py", line 358, in main
    qtrio.run(main_window)
  File "miniconda3/envs/sts/lib/python3.9/site-packages/qtrio/_core.py", line 512, in run
    return runner.outcomes.unwrap()
  File "miniconda3/envs/sts/lib/python3.9/site-packages/qtrio/_core.py", line 471, in unwrap
    result = self.trio.unwrap()
  File "miniconda3/envs/sts/lib/python3.9/site-packages/outcome/_impl.py", line 138, in unwrap
    raise captured_error
  File "miniconda3/envs/sts/lib/python3.9/site-packages/qtrio/_core.py", line 709, in trio_main
    result = await async_fn(*args)
  File "stskit/stskit/__main__.py", line 349, in main_window
    raise TaskDone()
  File "miniconda3/envs/sts/lib/python3.9/site-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "stskit/stskit/stsplugin.py", line 196, in receiver
    parser.close()
  File "miniconda3/envs/sts/lib/python3.9/xml/sax/expatreader.py", line 240, in close
    self.feed(b"", isFinal=True)
  File "miniconda3/envs/sts/lib/python3.9/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "miniconda3/envs/sts/lib/python3.9/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: unclosed token

Process finished with exit code 1
```

**Comment by topological-state** [comment]
nicht reproduziert
