### ISSUE TITLE
No such file or directory: qt/fahrplan.ui

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#13]
`Traceback (most recent call last):
  File ",,,\main.py", line 191, in fahrplan_clicked
    self.fahrplan_window = FahrplanWindow()
  File "...\stskit-master\fahrplan.py", line 151, in __init__
    uic.loadUi('qt/fahrplan.ui', self)
  File "...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyQt5\uic\__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyQt5\uic\Loader\loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
  File "...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyQt5\uic\uiparser.py", line 1020, in parse
    document = parse(filename)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\xml\etree\ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'qt/fahrplan.ui'`

Sehe dort zwar ein File 🤷‍♂️

**Comment by PianoRailways** [comment]
![image](https://user-images.githubusercontent.com/32222604/169713123-54c181ab-4c96-40f2-85e9-ab57ca1819e3.png)

`FileNotFoundError: [Errno 2] No such file or directory: 'qt\\fahrplan.ui'`
Warum mit 2 Backslashes??

**Comment by topological-state** [comment]
probier's mit der neuen version noch mal.
die 2 backslashes sind normal in python (escape-zeichen).
