### ISSUE TITLE
Absturz in verschiedenen Stellwerken

### ISSUE THREAD

**Issue by Eisenbahnfan2015** [topological-state/stskit#132]
Die Version auf dem master-Branch stürzt bei mir in verschiedenen Stellwerken (z.B.: Berlin-Schönefeld, Bautzen - Wilthen) immer wieder mit folgender Fehlermeldung ab:
```
+ Exception Group Traceback (most recent call last):
  |   File "~/Programme/stskit/stsdispo.py", line 4, in <module>
  |     main()
  |   File "~/Programme/stskit/stskit/__main__.py", line 358, in main
  |     qtrio.run(main_window)
  |   File "~/Programme/stskit/venv/lib/python3.10/site-packages/qtrio/_core.py", line 513, in run
  |     return runner.outcomes.unwrap()
  |   File "~/Programme/stskit/venv/lib/python3.10/site-packages/qtrio/_core.py", line 472, in unwrap
  |     result = self.trio.unwrap()
  |   File "~/Programme/stskit/venv/lib/python3.10/site-packages/outcome/_impl.py", line 213, in unwrap
  |     raise captured_error
  |   File "~/Programme/stskit/venv/lib/python3.10/site-packages/qtrio/_core.py", line 720, in trio_main
  |     result = await async_fn(*args)
  |   File "~/Programme/stskit/stskit/__main__.py", line 340, in main_window
  |     async with trio.open_nursery() as nursery:
  |   File "~/Programme/stskit/venv/lib/python3.10/site-packages/trio/_core/_run.py", line 954, in __aexit__
  |     raise combined_error_from_nursery
  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "~/Programme/stskit/stskit/stsobj.py", line 41, in time_to_minutes
    |     return dt.hour * 60 + dt.minute + round(dt.second / 60)
    | AttributeError: 'NoneType' object has no attribute 'hour'
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "~/Programme/stskit/stskit/__main__.py", line 273, in update_loop
    |     await self.zentrale.update()
    |   File "~/Programme/stskit/stskit/zentrale.py", line 115, in update
    |     self.planung.zuege_uebernehmen(self.client.zugliste.values())
    |   File "~/Programme/stskit/stskit/planung.py", line 1319, in zuege_uebernehmen
    |     self.korrekturen_definieren()
    |   File "~/Programme/stskit/stskit/planung.py", line 1704, in korrekturen_definieren
    |     result = self.zug_korrekturen_definieren(zug)
    |   File "~/Programme/stskit/stskit/planung.py", line 1710, in zug_korrekturen_definieren
    |     result = self.ziel_korrekturen_definieren(ziel)
    |   File "~/Programme/stskit/stskit/planung.py", line 1761, in ziel_korrekturen_definieren
    |     self._folgekorrektur_setzen(ziel, zid, folge_korrektur)
    |   File "~/Programme/stskit/stskit/planung.py", line 1805, in _folgekorrektur_setzen
    |     an1 = minutes_to_time(time_to_minutes(stamm_ziel.an) + stamm_ziel.mindestaufenthalt)
    |   File "~/Programme/stskit/stskit/stsobj.py", line 44, in time_to_minutes
    |     return round(dt.seconds / 60)
    | AttributeError: 'NoneType' object has no attribute 'seconds'
    +------------------------------------
```
In der Version 1.1.0 passiert das nicht.

**Comment by topological-state** [comment]
weiss nicht, woher das plötzlich kommt. kann es bei mir nicht reproduzieren. schau mal, ob das problem mit dem neuen fix 84ffe35 gelöst ist.

**Comment by Eisenbahnfan2015** [comment]
Damit funktioniert es. Es ist mir aber aufgefallen, dass ich 'kein "Gleis" in "nach"' an hatte. Nachdem ich es ausgeschaltet habe hat es dann auch wieder mit der alten Version funktioniert.

**Comment by topological-state** [comment]
Ich habe einen FAQ-Eintrag zu der "Gleis"-Einstellung erstellt. Die nächste Hauptversion (dev-graph, in Entwicklung), wird die Angabe nicht mehr benötigen.
