### ISSUE TITLE
fehler beim laden der anlagenkonfiguration (Huttwil 651)

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#30]
`2022-06-24 22:31:54,385 (anlage) ERROR: fehler beim laden der anlagenkonfiguration
Traceback (most recent call last):
  File "E:\Piano\Downloads\stskit-master\anlage.py", line 259, in update
    self.load_config(config_path)
  File "E:\Piano\Downloads\stskit-master\anlage.py", line 618, in load_config
    with open(p) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Piano\\.stskit\\651.json'
`
Plugin ist abgestürzt beim Anwählen des Gleisplans
`Traceback (most recent call last):
  File "E:\Piano\Downloads\stskit-master\main.py", line 193, in netz_clicked
    self.netz_window.update()
  File "E:\Piano\Downloads\stskit-master\gleisnetz.py", line 61, in update
    node_colors = [colormap.get(self.anlage.bahnhof_graph.nodes[key]['typ'], "r") for key in pos.keys()]
  File "E:\Piano\Downloads\stskit-master\gleisnetz.py", line 61, in <listcomp>
    node_colors = [colormap.get(self.anlage.bahnhof_graph.nodes[key]['typ'], "r") for key in pos.keys()]
KeyError: 'typ'`

**Comment by topological-state** [comment]
immer noch?

**Comment by PianoRailways** [comment]
scheint nicht mehr der Fall zu sein
