### ISSUE TITLE
Simmental: can't open gleisbelegung (list index out of range)

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#4]
```
Traceback (most recent call last):
  File "main.py", line 111, in gleisbelegung_clicked
    self.gleisbelegung_window.update()
  File "slotgrafik.py", line 191, in update
    self.grafik_update()
  File "slotgrafik.py", line 234, in grafik_update
    colors = [slot.farbe for slot in self._slots]
  File "slotgrafik.py", line 234, in <listcomp>
    colors = [slot.farbe for slot in self._slots]
  File "slotgrafik.py", line 110, in farbe
    elif self.zug.nummer < 2000:
  File "stsobj.py", line 324, in nummer
    return int(s.rsplit(maxsplit=1)[-1])
IndexError: list index out of range
```

**Comment by topological-state** [comment]
fixed in 4c22a53
are there trains without a number?
train numbers are just used for coloring, let's use gray for default.
