### ISSUE TITLE
Anschlussmatrix lässt sich nicht mehr starten und wirft Fehler aus

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#85]
```
Traceback (most recent call last):
  File "...\stskit-master\main.py", line 191, in matrix_clicked
    window = AnschlussmatrixWindow(self.zentrale)
  File "...\stskit-master\anschlussmatrix.py", line 545, in __init__
    self.update_actions()
  File "...\stskit-master\anschlussmatrix.py", line 564, in update_actions
    einblenden_enabled = display_mode and (len(self.anschlussmatrix.abfahrten_ausblenden) or
AttributeError: 'NoneType' object has no attribute 'abfahrten_ausblenden'
```

**Comment by topological-state** [comment]
sollte in der aktuellen version 6f52b65 schon behoben sein
